### PR TITLE
Minetweaker/Crafttweaker Support

### PR DESCRIPTION
**Pull request by tommyTT**
I saw on the reddit thread for ModTweaker that you were asking about how to implement support for Minetweaker3. Last weekend I wanted to learn the same thing and used your mod as a test subject. I implemented the Grindstone and Fluid Cooling Chamber support. Feel free to use and expand it as you see fit.

### CODE REVIEW

**Comment by Da-Technomancer** [comment]
It seems like you either didn't include some changes you made to build.gradle or there is something I am missing, but I won't be able to compile this until gradle is able to find the minetweaker libraries. If it's a build.gradle thing, what is the exact repository and dependency name?

Other than that, thank you very much for your help!

**Comment by tommyTT** [comment]
I see you added the "libs" folder to the gitignore, that's why that library wasn't in the commit. I used the same file as ModTweaker does, so simply including it in the libs folder should be sufficient:

`https://github.com/jaredlll08/ModTweaker/blob/master/libs/CraftTweaker-Dev-Full-1.10.2-3.0.10.jar`

You're welcome.

**Comment by StrangerSon71** [comment]
This should be redone.

**Comment by Da-Technomancer** [comment]
> This should be redone.

Crossroads has moved on to using JSON data based recipes natively now, and datapacks can add/remove/change recipes. There is no need for Crafttweaker support at this point.

**Pull request closed without merging**
